# Generated by Django 2.0 on 2017-12-04 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('hash', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField()),
            ],
        ),
    ]
