# Generated by Django 2.0 on 2017-12-15 18:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import files.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=200)),
                ('file', models.FileField(upload_to=files.models.hash_upload)),
                ('description', models.TextField(blank=True, max_length=200)),
                ('comment', models.TextField(blank=True, help_text='For internal use only...', max_length=200)),
                ('hash', models.CharField(editable=False, help_text='Auto-Generated SHA256 Hash (based on file content)', max_length=200, unique=True)),
                ('uuid', models.CharField(default=uuid.uuid4, editable=False, help_text='Auto-Generated random unique ID', max_length=200, unique=True)),
                ('filesize', models.IntegerField(blank=True, editable=False, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('filetype', models.CharField(max_length=100)),
                ('ext', models.CharField(blank=True, max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('project_type', models.CharField(choices=[(1, 'Publication'), (2, 'Thesis')], default=1, max_length=100)),
                ('description', models.TextField(blank=True, max_length=400)),
                ('owner', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='file',
            name='filetype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='files.FileType'),
        ),
        migrations.AddField(
            model_name='file',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.Project'),
        ),
    ]
