# Generated by Django 2.0 on 2017-12-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20171205_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='filesize',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
