# Generated by Django 2.0 on 2017-12-05 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0003_files_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='hash',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
