# Generated by Django 2.0 on 2017-12-05 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20171205_0923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='filesize',
            field=models.IntegerField(null=True),
        ),
    ]
