# Generated by Django 2.0 on 2017-12-05 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0009_auto_20171205_0946'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Files',
            new_name='File',
        ),
    ]
