# Generated by Django 2.0 on 2017-12-06 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0012_auto_20171206_0831'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='file',
            name='hash',
            field=models.CharField(editable=False, max_length=200, unique=True),
        ),
    ]
