# Generated by Django 2.0 on 2017-12-14 09:11

from django.db import migrations, models
import files.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0013_auto_20171206_0921'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='file',
            field=models.FileField(upload_to=files.models.hash_upload),
        ),
    ]
