# Generated by Django 2.0 on 2017-12-15 10:31

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0014_auto_20171214_0911'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100)),
                ('ext', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='file',
            name='uuid',
            field=models.CharField(default=uuid.uuid4, editable=False, max_length=200, unique=True),
        ),
    ]
