# Generated by Django 2.0 on 2017-12-15 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0016_project_owner'),
        ('files', '0015_auto_20171215_1031'),
    ]

    operations = [
    ]
