# Generated by Django 2.0 on 2017-12-15 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0017_merge_20171215_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='comment',
            field=models.CharField(default=None, editable=False, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='description',
            field=models.CharField(default=None, editable=False, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='file',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='files.FileType'),
        ),
        migrations.AlterField(
            model_name='filetype',
            name='ext',
            field=models.CharField(blank=True, max_length=10),
        ),
    ]
