# Generated by Django 2.0 on 2017-12-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0018_auto_20171215_1456'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
