# Generated by Django 2.0 on 2017-12-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0019_auto_20171215_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='comment',
            field=models.TextField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='file',
            name='description',
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
